"""empty message

Revision ID: 26008c338a6a
Revises: fe4457be0ef9
Create Date: 2021-03-18 16:29:37.813419

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '26008c338a6a'
down_revision = 'fe4457be0ef9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('todos', sa.Column('completed', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###

    # Change with some custom code - take care of already existing data
    op.execute('UPDATE todos SET completed = False WHERE completed IS NULL;')
    op.alter_column('todos', 'completed', nullable=False)


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('todos', 'completed')
    # ### end Alembic commands ###
