"""empty message

Revision ID: 9246b42caeeb
Revises: 9f6372988a05
Create Date: 2021-03-19 08:29:48.879676

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9246b42caeeb'
down_revision = '9f6372988a05'
branch_labels = None
depends_on = None


def upgrade():
    # Change with some custom code - set default values
    op.execute("INSERT INTO lists (name) VALUES ('Default');")
    op.execute("UPDATE todos SET list_id = (SELECT id FROM lists WHERE name='Default' LIMIT 1) WHERE list_id IS NULL;")
    
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('todos', 'list_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    # ### end Alembic commands ###

    # Change with some custom code - reset default values
    op.execute("UPDATE todos SET list_id = NULL WHERE list_id = (SELECT id FROM lists WHERE name='Default' LIMIT 1);")
    op.execute("DELETE FROM lists WHERE name='Default';")
