"""empty message

Revision ID: 9f6372988a05
Revises: 26008c338a6a
Create Date: 2021-03-19 08:26:52.858541

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9f6372988a05'
down_revision = '26008c338a6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('lists',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('todos', sa.Column('list_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'todos', 'lists', ['list_id'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Custom: need to specify name of constraint (looked up from pgadmin)
    op.drop_constraint('todos_list_id_fkey', 'todos', type_='foreignkey')
    op.drop_column('todos', 'list_id')
    op.drop_table('lists')
    # ### end Alembic commands ###
